### PR TITLE
Initial stab at a tutorial for Streaming Hadoop

### PR DESCRIPTION
**Pull request by buggtb**
Written a tutorial for Streaming Hadoop on JAAS. Needs testing ready for deployment next week if possible.

### CODE REVIEW

**Comment by buggtb** [comment]
There is an update or two relating to the stuff the users have to do, someone needs to redeploy the tutorial before validating the steps.

**Comment by caldav** [comment]
@buggtb thanks for letting us know, the demo should update with new commits. Someone from the JAAS team will be doing some testing. Nicely structured tutorial btw.

**Comment by spencerbygraves** [comment]
@caldav Some of the screenshots have a broken Google logo, please can we use the ones below. Thanks.

#### hadoopbundle.png

image

#### kafkaconfig.png

image

#### kafkadeploy.png

image

#### overview.png

image

**Comment by buggtb** [comment]
Updated the issues and images. Thanks chaps.

**Comment by caldav** [comment]
"Don't merge" until we have an announcement date. @buggtb, I presume there is a blog post to go with it, when should the tutorial go live?

**Comment by clagom** [comment]
@caldav I talked with Katie, Tutorial should go live before Thursday this week. Are we ok to merge?

**Pull request merged**
