### PR TITLE
Update graphical snaps

### PR DESCRIPTION
**Pull request by Saviq**
## Done

Reworked and updated and the mir-kiosk set of tutorials.

## TODO

Provide redirects:
- /tutorial/graphical-snaps → /tutorial/secure-ubuntu-kiosk
- /tutorial/graphical-snaps-xwayland → /tutorial/x11-kiosk

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8016/](http://0.0.0.0:8016/)

### CODE REVIEW

**Comment by pmahnke** [comment]
@WillMoggridge do you know the best way to add redirects to this app?

**Comment by WillMoggridge** [comment]
I'm looking at options now, and the easiest way to manage them.

**Comment by Saviq** [comment]
Seems like we have the redirects queued up, can we please deploy this and #829 then? Thanks!

**Comment by Saviq** [comment]
@anthonydillon here's the PR we talked about - can we get this merged/deployed please?

**Pull request merged**
