### PR TITLE
Reformat deployment tooling

### PR DESCRIPTION
**Pull request by didrocks**
Switch to a new and more robust deployment tooling. This one is now out of tree (no need to check in binaries anymore), and support both markdown and google doc. It will be downloaded and updated automatically if a new releases is available.
Note that the generate binary defaults handle a new directory structure and slightely enhance the API, keeping it still compatible. It can handle multiple directories (markdown or google doc reference file) so that source file can be in any directory, and support multiple source types.
Added as well some serve binaries, which will enable automated markdown editing and live refresh of content.
Do some enhancement on the html side to remove the need for patching image paths after generating their tutorials.
Handle events and format source in yaml format. Images and assets can now just be relative to them (and will be in /api/assets)
Change index.ubuntu-template.html to a more logical .inc extension, as it's now downloaded as a file part.

Note once this is merged, the deploy jenkins job needs to change to simply call bin/generate as in my job. You can remove all rm/image path replacement calls.

### CODE REVIEW

**Comment by didrocks** [comment]
Thanks for the review, here are some feedbacks:
1. I disagree with changes the generated partial pages back from .inc to .html. Indeed, since you changed its layout, it's not a standalone html file (contrary to webcomponents or the way it was). Renaming it to .html will make people using the generation live tool thinking they can just open that file in the browser and hack on it, which they can't. If you want to remove the ajax hack you added and convert it back to a real html page standalone webcomponent, I'm fine with renaming it back thus.
2. changing this will complexify a lot the live preview tooling. The idea is that you have two output paths: the codelabs and API ones. We can add another path if needed, but I can completely sees events having other kinds of assets like html files and such.
Another way it to have this asset directory in the root directories, and move static images (like the html icon) there, and the generated events assets in assets/events/. Tell me what you think.
The reason I prefer to have those assets related to API in the api/ directory is that I can envision an event partner pulling our codelabs to their API and wanted to link their generated assets. Thoughts?

On the request:
The api/ (and `codelabs.json`) directory stands there due to the example, indeed, so that you can load your website in your testing environment. If you are fine with it, let's indeed remove it (doing it right now). Then, you can write a markdown file example as you told and just refers it with `bin/serve <this markdown file>`. The net benefit is that it won't polluate your repository anymore as all those will be in a temporary directory while you test it :)

**Comment by didrocks** [comment]
Removal of example done. Better indeed to not have those files duplications!
I suggest that you create the markdown file in an `examples/` directory (not under `metadata` or it will be picked up by the generation tool!), and for testing you just need to do: `bin/serve examples/` and all example will be served on the live port :)

**Comment by WillMoggridge** [comment]
That examples serve is a nice idea, seems like a good way to go forward.

I find `.inc` extensions make me feel uneasy. It is something that I remember previously in PHP and was a bit of a pain. I also don't really want to be locked into the current set up with AJAX.
As for people thinking they can hack the files, I don't know how much it can change. I feel there is only so much we can do before it makes are job a little harder as a result. The files will be gitignored, so that make it a little more transparent.


For API use, the API should just point to images where they are hosted. I would think it shouldn't make much of a difference where they are. A reason I want to keep this separate is that maybe in the future we may want to replace the API folder with a backend service to generate dynamically.

It is a valid point about keeping generated images separate though. A `media` or `assets` folder is fine by me for that purpose. I would be very happy with that. It will need to be added to the `polymer.json` build files.

**Comment by didrocks** [comment]
Ok, let's meet in the middle. I'm ok for moving them to `.codelab`, that way, the confusion (remember that there is a `serve` command which output them in a temporary directory) for .html while can't be opened will be mitigated. Sounds find to you?

On the API, I want to have input directory. I don't think you are going to ship the `metadata/` directory. Remember as well that those declaration can be out of that directory (multiple repos example), we need to copy them in a place. The `api/` directory change for a dynamic content is a good point, so let's move that to `images/events` directory for now.

If you +1 on both, I'm going to have a look at that and repropose something tomorrow, sounds good?

**Comment by nottrobin** [comment]
I don't have an opinion on most of this, but could we please keep the extension of `.html` for generated HTML files? It makes it much clearer for anyone coming to the codebase immediately what these files contain, and it will mean that any editors highlight the syntax correctly.

Also, I'd rather usually make changes to existing project structure only when it either solves an explicit problem that we're having or when there's clear team consensus. All developers are opinionated so we could end up arguing indefinitely about our individual preferences. I don't think it's worth having a protracted discussion to rename `.html` right now.

**Comment by didrocks** [comment]
Just pushed the change for the API "images/events/".

You will find as well there the commit for the extension rename. I have synced the generator code with this in this branch: https://github.com/ubuntu/tutorial-deployment/tree/path-adapt-for-websites. The specific renaming path is https://github.com/ubuntu/tutorial-deployment/commit/d268744dea5ac3f9c50eed24448776a5202719bd.

Can you please give it another look?
For this to be deployed, we need:
- the final +1 here
- once this is done, I'll push the changes to the generator master, tag a release -> this will create the new binaries automatically from Travis CI.
- change to the jenkins job for deployment to mirror the one I did in the `-didrocks` one. (use the generator one).
- then, this can be merged and we can redeploy the website.

Finally, I'll be able to do my followup merge proposal for the live refresh feature (which is already implemented in the generator side).

**Comment by WillMoggridge** [comment]
OK, sounds great

**Comment by didrocks** [comment]
As told on IRC:
"Compatible binaries are now published, you can merge and update the jenkins job deployment. Keep me posted once done so that I do the followup MP based on fresh master."

**Pull request merged**
