### PR TITLE
[Translation][French] Translation in french of setting up lxd tutorial

### PR DESCRIPTION
**Pull request by Winael**
This is a french translation of the tutorial about setting up lxd on Ubuntu 16.04

### CODE REVIEW

**Comment by caldav** [comment]
@Winael any update?

**Comment by Winael** [comment]
Hi @caldav, 
sorry I haven't have the time to finish my review. It still in WIP in my Todo list :) 
I think I will ahve more time next week to do it

Cheers

**Comment by Winael** [comment]
Hi @caldav 

I finally found some time to correct translation according to your recommandation. Hoping it's good now

Cheers
Winael

**Comment by caldav** [comment]
@Winael I've added some format fixes and a language switcher at the top, but it looks great overall, thank you! :+1:

**Comment by Winael** [comment]
@caldav, nice :) it's encouraging to do more translation. Thx

Le jeu. 26 oct. 2017 à 16:58, David Callé <notifications@github.com> a
écrit :

**Pull request merged**
